# DESCRIPTION: 	
# Builds and tests projects in the repository

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)

# Trigger is overridden in azdo pipeline configuration.
trigger: none

variables:
  - template: ./ci-variables.yml

jobs:
  jobs:
  - job: CodeChecks
    pool:
      vmImage: ${{ variables.WindowsVmImage }}
    steps:
    - template: ./jobs/checkCode.yml
      parameters:
        DotNetVersion: ${{ variables.DotNetVersion }}
        SolutionName: ${{ variables.SolutionName }}

  - job: BuildTestPublish
    pool:
      vmImage: ${{ variables.WindowsVmImage }}
    steps:
    - template: ./jobs/update-semver.yml
    - template: ./jobs/build.yml
      parameters:
        RunUnitTest: true
        RunComponentGovernance: false