# DESCRIPTION: 	
# Builds and tests projects in the repository

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)

# Trigger is overridden in azdo pipeline configuration.
trigger: none

variables:
  - template: ./ci-variables.yml

stages:
  # Run for PRs and check-ins to the main branch. Run automatically.
  - stage: Build

    jobs:
    - job: BuildTest
      pool:
        vmImage: ${{ variables.WindowsVmImage }}
      steps:
      # - template: ./jobs/update-semver.yml
      - template: ./jobs/build.yml