parameters:
  - name: RunUnitTest
    default: true
  - name: RunComponentGovernance
    default: false

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    inputs:
      command: "build"
      # arguments: '--configuration $(BuildConfiguration) --no-incremental -p:ContinuousIntegrationBuild=true -p:AssemblyVersion="$(SetVariablesFromGitVersion.AssemblySemVer)" -p:FileVersion="$(SetVariablesFromGitVersion.AssemblySemFileVer)" -p:InformationalVersion="$(SetVariablesFromGitVersion.InformationalVersion)" -p:Version="$(SetVariablesFromGitVersion.MajorMinorPatch)" -warnaserror'
      arguments: '--configuration $(BuildConfiguration) --no-incremental -p:ContinuousIntegrationBuild=true -warnaserror'
    displayName: "Build Source Projects"

  - task: DotNetCoreCLI@2
    inputs:
      command: "test"
      arguments: "--no-build --configuration $(BuildConfiguration)"
      publishTestResults: true
    displayName: "Run all tests"
